name = "Screenshots"
uuid = "1e4f4ae9-b882-4467-a09e-1fde90e27c49"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"

[compat]
julia = "1"
FileIO = "1.16"
ImageMagick = "0.7.9"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "FixedPointNumbers", "Test"]
